### ISSUE TITLE
CVS: Preflight Checklist / Milestone

### ISSUE THREAD

**Issue by shanecarr1** [githubcustomers/avocado#20]
# Pre-migration checklist

#### Prepare an inventory

- [ ] Make a list of all repositories that need to be migrated
- [ ] Categorize/Group the repositories depending on the different source platforms
- [ ] Create a source-to-target matrix/checklist for each of the categorized/grouped repositories
- [ ] Determine potential Organization that will be created in the target platform

#### Ensure Migration tools pre-requisites are met

- [ ] [Export tool prerequisites](./0.3.1.0-tools-prerequisites-export.md) your migration source platform
- [ ] [Import tool prerequisites](./0.3.1.5-tools-prerequisites-import.md) your migration target platform

#### Perform cleanup

- [ ] Use this time of migration to only export the things that matter and do a [repository cleanup](./clean-up-repositories/index.md)

#### Determine the scope of migration

For each of the repositories you want to migrate:
- [ ] Check the [scope of the migration](./1.4-pre-migration-scope.md) to be executed
- [ ] [Decide the tools](./0.3-tools-overview.md) and flows that you will be using for the migration

#### Dry run migration

- [ ] Plan some time to execute a dry run of the migration (if possible on a sandbox environment)
  - Please note that a dry run is used to get the right "shape" and how the customer exactly wants the conversion to look like. The Professional Services team will use these as a conversation to explore options.

#### Plan and execute the actual migration

- [ ] Create a communication plan for the migration
- [ ] Plan some time to execute the actual migration
- [ ] Create backups if necessary
- [ ] Complete the post-migration steps
